apiVersion: viewnext.com/v1alpha1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: operator-helm
    app.kubernetes.io/managed-by: kustomize
  name: nginx-sample
spec:
  # TODO(user): Add fields here
