# This rule is not used by the project operator-kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the vn.viewnext.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: test-editor-role
rules:
- apiGroups:
  - vn.viewnext.com
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vn.viewnext.com
  resources:
  - tests/status
  verbs:
  - get
