# This rule is not used by the project operator-kubebuilder itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to vn.viewnext.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: test-viewer-role
rules:
- apiGroups:
  - vn.viewnext.com
  resources:
  - tests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vn.viewnext.com
  resources:
  - tests/status
  verbs:
  - get
