# permissions for end users to edit nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-helm
    app.kubernetes.io/managed-by: kustomize
  name: nginx-editor-role
rules:
- apiGroups:
  - viewnext.com
  resources:
  - nginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - viewnext.com
  resources:
  - nginxes/status
  verbs:
  - get
