apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator-helm.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: description
  displayName: nginx-test
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nginx
  - viewnext
  links:
  - name: Operator Helm
    url: https://operator-helm.domain
  maintainers:
  - email: vriverofernandez@viewnext.com
    name: name1
  maturity: alpha
  provider:
    name: viewnext.com
  version: 0.0.0
